language: csharp
mono: latest
sudo: required
dist: trustly
dotnet: 3.0
solution: iso8583net.sln
before_script:
- nuget install docfx.console -ExcludeVersion
- export DOCFX_TOOL="mono docfx.console/tools/docfx.exe"
script:    # the following commands are just examples, use whatever your build process requires
- dotnet restore
- dotnet build
  
