language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
solution: iso8583net.sln
script:    # the following commands are just examples, use whatever your build process requires
  - dotnet restore
  - dotnet build